### ISSUE TITLE
European dates layout

### ISSUE THREAD

**Issue by abraovic** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#153]
Hi,

Is there a way, like some option or so to show dates in **European layout**, so that **Sunday is a last day of a week** instead of first?

Thanks,
Ante.

**Comment by Wikinaut** [comment]
See https://api.jqueryui.com/datepicker/#option-firstDay .

Simply set the first day of the week: Sunday is 0, Monday is 1, etc.
Initialize the MDP with the firstDay option specified.

**Comment by Wikinaut** [comment]
Pls. close this issue, if my tip was what you were looking for.

**Comment by abraovic** [comment]
Hi, thanks a lot @Wikinaut
