### ISSUE TITLE
How do I localize the MDP

### ISSUE THREAD

**Issue by trickinicki** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#189]
Is it possible to localize your great tool?

**Comment by Plaristote** [comment]
I've done it once, so yes, definitely possible.

But... if in the past few months you've found the answer to this question, I'll take it.
Because though I can definitely see it properly translated, I cannot figure out for the life of me which piece of code is responsible for that.

I'll also keep this updated if I find out how the hell it works.

**Comment by Plaristote** [comment]
I've got the line responsible for the translation.

```
$.datepicker.setDefaults($.datepicker.regional['en']);
```

Apparently you can use this kind of source for jquery-ui.datepicker in order to have the proper locale:
```
<script type="text/javascript" src="/scripts/jquery.ui.datepicker-it.js"></script>
```

**Comment by trickinicki** [comment]
Sorry for ignoring your advice fo such a log time. I'm not verry often in the github so I just missed it.
The way you describe is working perfectly....

Thanks

**Comment by valugi** [comment]
Hi,
Sorry to bring this up again, but I do not understand how to inject a locale into the MDP configuration. The example of @Plaristote is working directly with the datepicker object and not with the multiDatesPicker one. 

Can you please clarify?
Thanks

**Comment by trickinicki** [comment]
The code I used:
```
$(function () {
  $("#PublishFromBox").datepicker({
    dateFormat: "dd.mm.yy",
    regional: "de"
  });
```

**Comment by trickinicki** [comment]
Sorry abot that, got mixed up with another project...
... here the right One or just some sample Code out of it. The localization is in the events.js file.
[Datepicker Localized.zip](https://github.com/dubrox/Multiple-Dates-Picker-for-jQuery-UI/files/2592805/Datepicker.Localized.zip)
