### ISSUE TITLE
Multidatespicker localized in spanish

### ISSUE THREAD

**Issue by yoburtu** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#250]
Hi!,

congratulations for your development!.

How can I configure the texts of months and days in spanish?. And put start week to Monday.

Best regards!.

**Comment by dubrox** [comment]
It is already possible, just use the localization feature of jQuery UI datepicker: https://stackoverflow.com/questions/494958/how-do-i-localize-the-jquery-ui-datepicker
