### ISSUE TITLE
MultiDates Picker / Disable dates 

### ISSUE THREAD

**Issue by philquarter24** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#264]
I'm using Multi Dates Picker for Jquery  for a booking application and it works well !
To disable "allready booked" dates, i use  and .inc file containing dates to disable.
example:  
'07/31/'+y, '08/01/'+y, '08/02/'+y, '08/03/'+y, '08/04/'+y, '08/05/'+y, '08/06/'+y, // resa 21-138  
'08/07/'+y, '08/08/'+y, '08/09/'+y, '08/10/'+y, '08/11/'+y, '08/12/'+y, '08/13/'+y, // resa 21-154  
'08/14/'+y, '08/15/'+y, '08/16/'+y, '08/17/'+y, '08/18/'+y, '08/19/'+y, '08/20/'+y // resa 21-163   
For the actual year it works well, the y parameter is correctly supported.
But if i want to disable a date for the next year (ex 2022) it does't work.
I've tried:  '08/20/'+2022   format,  '08/20/'+y+1  format , '08/20/2022' format ...  it still does'nt work.
What is the correct format to disable any date / year ?
Thanks for yr help.

**Comment by dubrox** [comment]
I could not reproduce:
https://jsfiddle.net/om2gu879/

```js
var date = new Date();
$('#mdp-demo').multiDatesPicker({
	// disable the 1st and 3rd of the current month
	addDisabledDates: ['12/12/2024', '1/1/2025'],
  numberOfMonths: 2,
});
```
![image](https://github.com/user-attachments/assets/c2ef082d-e470-4781-84d6-78598acb62ed)

Please share a jsfiddle link (or similar) next time.
