### ISSUE TITLE
Input section cannot appear anymore

### ISSUE THREAD

**Issue by obaurens** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#278]
Hello

When multidate calendar is called from input, then it cannot appear anymore (since 2 days now).
You can check it from: [https://jsfiddle.net/xbk3bwd1/2/]

Thanks a lot for your support. Have a nice day
Best Regards

**Comment by dubrox** [comment]
I'm reverting the main branch to the previous commit that changed the logic in the MDP. Waiting for the change to propagate.

Sorry for the inconvenience and thanks for the heads up :)

**Comment by dubrox** [comment]
For some reason, [the CDN link used in the demos](https://cdn.jsdelivr.net/gh/dubrox/Multiple-Dates-Picker-for-jQuery-UI@master/jquery-ui.multidatespicker.js) is not getting the update yet, but the links to [the new default branch name `main`](https://cdn.jsdelivr.net/gh/dubrox/Multiple-Dates-Picker-for-jQuery-UI@main/jquery-ui.multidatespicker.js) and [the one specific to the 1.6.6 version tag](https://cdn.jsdelivr.net/gh/dubrox/Multiple-Dates-Picker-for-jQuery-UI@1.6.6/jquery-ui.multidatespicker.js) are pointing to the latest working version.

**Comment by obaurens** [comment]
Hello again,

And thanks a lot for your great support. Your comment helps us to solve issue.

Have a very nice day
regards
