### ISSUE TITLE
get picked dates

### ISSUE THREAD

**Issue by gregoriouseas** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#30]
anyone knows how to get the count of picked dates on the calendar into a php variable.

really need help here

best regards !

**Comment by frosamga** [comment]
`function days() {

      var length = $('#full-year').multiDatesPicker("getDates").length;
      for(i = 0; i<length;i++){
           alert($('#full-year').multiDatesPicker("getDates")[i]);
     }
}`
