### ISSUE TITLE
value attribute of altField does not pre-select dates

### ISSUE THREAD

**Issue by scottrouse** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#45]
In the example documentation, you demo preselecting dates by setting the value attribute on a field.

<code>value="04/19/2012,04/21/2012"</code>

This doesn't do anything.

![Screenshot_1_21_13_9_16_PM](https://f.cloud.github.com/assets/220778/85061/c0fe774c-6439-11e2-84cc-31a08d71239b.png)

**Comment by msyadav88** [comment]
Below works for me.
value="04/19/2012, 04/21/2012"
There must be space after comma.
