### ISSUE TITLE
Trying to resetDates

### ISSUE THREAD

**Issue by hcanovas** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#51]
Hello,

I'm trying to use resetDates to clean my multiDatesPicker but no successfull.

My code is:

$(".add_days").multiDatesPicker('resetDates','disabled');
$(".add_days").multiDatesPicker();

I tryied it with $(".add_days").multiDatesPicker('resetDates','picked'), and without declaring the method the second time, but none took effect.

Anyone can help me? Thanks.

**Comment by pimkle** [comment]
$(".add_days").multiDatesPicker('resetDates');
